- debug:
    msg:
    - "{{deployment_mode}}"
    - "{{stage}}"
    - "{{region}}"
    - "{{service}}"
    - "{{destination_alz_path}}"
    
- include_tasks: "load_deployments_alz.yaml"
  loop: "{{topology.deployments[deployment_mode][stage][region].keys()}}"
  loop_control:
    loop_var: service
  when: stage == 'alz'

